# Generated by Django 2.0.2 on 2018-03-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheliangjilu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='车主（签字）')),
                ('phone', models.CharField(max_length=100, verbose_name='车主联系电话')),
                ('chepai', models.CharField(max_length=100, verbose_name='车牌')),
                ('chuche', models.CharField(max_length=100, verbose_name='出车时间')),
                ('yongtu', models.CharField(max_length=100, verbose_name='出车用途')),
                ('licheng', models.CharField(max_length=100, verbose_name='行驶里程')),
                ('qianzi', models.CharField(max_length=100, verbose_name='董事长签字')),
                ('beizhu', models.CharField(max_length=255, verbose_name='备注')),
            ],
            options={
                'verbose_name': '车辆使用记录',
                'verbose_name_plural': '车辆使用记录',
            },
        ),
        migrations.CreateModel(
            name='Gongzhangjilu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='使用人（签字）')),
                ('phone', models.CharField(max_length=100, verbose_name='使用人联系电话')),
                ('shiyou', models.CharField(max_length=100, verbose_name='使用事由')),
                ('qianzi', models.CharField(max_length=100, verbose_name='董事长签字')),
                ('beizhu', models.CharField(max_length=255, verbose_name='备注')),
            ],
            options={
                'verbose_name': '公章使用记录',
                'verbose_name_plural': '公章使用记录',
            },
        ),
        migrations.CreateModel(
            name='Zhuanheshe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
                ('faren', models.CharField(max_length=255, verbose_name='法人')),
                ('phone', models.CharField(max_length=255, verbose_name='法人联系手机')),
            ],
            options={
                'verbose_name': '专合社',
                'verbose_name_plural': '专合社',
            },
        ),
    ]
