# Generated by Django 2.0.2 on 2018-03-30 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gongzhangjilu',
            old_name='shiyou',
            new_name='shiyong',
        ),
    ]
