# Generated by Django 2.0.2 on 2018-03-30 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('create_time', models.DateField(auto_now=True, verbose_name='发布时间')),
                ('chakan', models.IntegerField(verbose_name='查看数')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='文章分类')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='公司名')),
                ('tel', models.CharField(max_length=100, verbose_name='电话')),
                ('chuanzhen', models.CharField(max_length=100, verbose_name='传真')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('email', models.CharField(max_length=100, verbose_name='邮件')),
                ('youbian', models.CharField(max_length=100, verbose_name='邮编')),
                ('url', models.CharField(max_length=100, verbose_name='公司网址')),
                ('desc', models.TextField(verbose_name='公司简介')),
                ('wenhua', models.TextField(verbose_name='企业文化')),
                ('lianxi', models.TextField(verbose_name='联系我们')),
            ],
            options={
                'verbose_name': '公司信息',
                'verbose_name_plural': '公司信息',
            },
        ),
        migrations.CreateModel(
            name='Fengjing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='风景名')),
                ('imagea', models.ImageField(upload_to='img/%Y/%d', verbose_name='风景图片1')),
                ('imageb', models.ImageField(upload_to='img/%Y/%d', verbose_name='风景图片2')),
                ('imagec', models.ImageField(upload_to='img/%Y/%d', verbose_name='风景图片3')),
                ('imaged', models.ImageField(upload_to='img/%Y/%d', verbose_name='风景图片4')),
                ('imagee', models.ImageField(upload_to='img/%Y/%d', verbose_name='风景图片5')),
                ('imagef', models.ImageField(upload_to='img/%Y/%d', verbose_name='风景图片6')),
                ('content', models.TextField(verbose_name='风景说明')),
            ],
            options={
                'verbose_name': '风景',
                'verbose_name_plural': '风景',
            },
        ),
        migrations.CreateModel(
            name='FengjingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='风景名')),
            ],
            options={
                'verbose_name': '风景分类',
                'verbose_name_plural': '风景分类',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='产品名')),
                ('price', models.FloatField(verbose_name='产品价格')),
                ('imagea', models.ImageField(upload_to='img/%Y/%d', verbose_name='产品图片1')),
                ('imageb', models.ImageField(upload_to='img/%Y/%d', verbose_name='产品图片2')),
                ('imagec', models.ImageField(upload_to='img/%Y/%d', verbose_name='产品图片3')),
                ('imaged', models.ImageField(upload_to='img/%Y/%d', verbose_name='产品图片4')),
                ('imagee', models.ImageField(upload_to='img/%Y/%d', verbose_name='产品图片5')),
                ('imagef', models.ImageField(upload_to='img/%Y/%d', verbose_name='产品图片6')),
                ('content', models.TextField(verbose_name='产品说明')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='产品分类名')),
            ],
            options={
                'verbose_name': '产品分类',
                'verbose_name_plural': '产品分类',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='链接名')),
                ('url', models.CharField(max_length=200, verbose_name='链接地址')),
            ],
            options={
                'verbose_name': '友情链接表',
                'verbose_name_plural': '友情链接表',
            },
        ),
        migrations.CreateModel(
            name='Lunbo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='图片名')),
                ('image', models.ImageField(upload_to='ima/%Y/%d', verbose_name='轮播图')),
                ('nick', models.CharField(max_length=100, verbose_name='测试')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Rongyu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='荣誉名字')),
                ('image', models.ImageField(upload_to='image/%Y/%d', verbose_name='荣誉图片')),
                ('desc', models.TextField(verbose_name='荣誉描述')),
            ],
            options={
                'verbose_name': '荣誉',
                'verbose_name_plural': '荣誉',
            },
        ),
        migrations.CreateModel(
            name='Tuandui',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名字')),
                ('zhiwei', models.CharField(max_length=50, verbose_name='职位')),
                ('image', models.ImageField(upload_to='image/%Y/%d', verbose_name='头像')),
                ('desc', models.TextField(verbose_name='人物描述')),
            ],
            options={
                'verbose_name': '团队',
                'verbose_name_plural': '团队',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.GoodsCategory', verbose_name='产品分类'),
        ),
        migrations.AddField(
            model_name='fengjing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.FengjingCategory', verbose_name='风景分类'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.ArticleCategory', verbose_name='文章分类'),
        ),
    ]
