# Generated by Django 2.0.2 on 2018-04-03 17:42

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(default='', upload_to='media/image/%Y/%d', verbose_name='公司LOGO'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='网站简介'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='lianxi',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='wenhua',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='企业文化'),
        ),
        migrations.AlterField(
            model_name='fengjing',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='风景描述'),
        ),
        migrations.AlterField(
            model_name='fengjing',
            name='imagea',
            field=models.ImageField(upload_to='media/image/%Y/%d', verbose_name='风景图片1'),
        ),
        migrations.AlterField(
            model_name='fengjing',
            name='imageb',
            field=models.ImageField(upload_to='media/image/%Y/%d', verbose_name='风景图片2'),
        ),
        migrations.AlterField(
            model_name='fengjing',
            name='imagec',
            field=models.ImageField(upload_to='media/image/%Y/%d', verbose_name='风景图片3'),
        ),
        migrations.AlterField(
            model_name='fengjing',
            name='imaged',
            field=models.ImageField(upload_to='media/image/%Y/%d', verbose_name='风景图片4'),
        ),
        migrations.AlterField(
            model_name='fengjing',
            name='imagee',
            field=models.ImageField(upload_to='media/image/%Y/%d', verbose_name='风景图片5'),
        ),
        migrations.AlterField(
            model_name='fengjing',
            name='imagef',
            field=models.ImageField(upload_to='media/image/%Y/%d', verbose_name='风景图片6'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='商品描述'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='imagea',
            field=models.ImageField(upload_to='media/image/%Y/%d', verbose_name='产品图片1'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='imageb',
            field=models.ImageField(upload_to='media/image/%Y/%d', verbose_name='产品图片2'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='imagec',
            field=models.ImageField(upload_to='media/image/%Y/%d', verbose_name='产品图片3'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='imaged',
            field=models.ImageField(upload_to='media/image/%Y/%d', verbose_name='产品图片4'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='imagee',
            field=models.ImageField(upload_to='media/image/%Y/%d', verbose_name='产品图片5'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='imagef',
            field=models.ImageField(upload_to='media/image/%Y/%d', verbose_name='产品图片6'),
        ),
        migrations.AlterField(
            model_name='lunbo',
            name='image',
            field=models.ImageField(upload_to='media/image/%Y/%d', verbose_name='轮播图'),
        ),
        migrations.AlterField(
            model_name='rongyu',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='荣誉描述'),
        ),
        migrations.AlterField(
            model_name='rongyu',
            name='image',
            field=models.ImageField(upload_to='media/image/%Y/%d', verbose_name='荣誉图片'),
        ),
        migrations.AlterField(
            model_name='tuandui',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='tuandui',
            name='image',
            field=models.ImageField(upload_to='media/image/%Y/%d', verbose_name='头像'),
        ),
    ]
