# Generated by Django 2.0.2 on 2018-04-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180403_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(upload_to='media/image/%Y/%d', verbose_name='公司LOGO'),
        ),
    ]
